### ISSUE TITLE
Create Branch Types Llist

### ISSUE THREAD

**Issue by Kangaru-Ras** [amakentech/enibo-core-ui#18]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/amakentech/enibo-core-ui/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Amaken's [Code of Conduct](https://github.com/amakentech/enibo-core-ui/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This GitHub issue is to track the creation of a Branch Types List, which will contain the following fields:

1. **Branch Type Code**
2. **Branch Type Name**
3. **Description**
4. **Modified By**
5. **Modified On**

### To-Do
- [ ] Create Branch Types List
- [ ] Implement fields: Branch Type Code, Branch Type Name, Description, Modified By, Modified On
- [ ] Ensure proper functionality and data storage for the list

### Additional Information
Any additional details, considerations, or notes can be added here.
