### ISSUE TITLE
Create Transactions Types list page

### ISSUE THREAD

**Issue by Kangaru-Ras** [amakentech/enibo-core-ui#20]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/amakentech/enibo-core-ui/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Amaken's [Code of Conduct](https://github.com/amakentech/enibo-core-ui/blob/main/.github/CODE_OF_CONDUCT.md)

### List Details
- **List Name**: Transactions Types
- **Navigation Path**: Administration / Static Data / Transaction Types
- **Columns**:
  1. Transaction Type Code
  2. Transaction Type Description
  3. Currency
  4. Modified On
  5. Modified By

### To-Do
- [ ] Create the Transactions Types list page.
- [ ] Implement the Transaction Type Code column.
- [ ] Implement the Transaction Type Description column.
- [ ] Implement the Currency column.
- [ ] Implement the Modified On column.
- [ ] Implement the Modified By column.

### Additional Information
Any additional details, considerations, or notes can be added here.
